name: Build OpenWrt BE

on:
  repository_dispatch:
  workflow_dispatch:

env:
  DEVICE_NAME: Unkonwn
  DATE: Unkonwn
  FIRMWARE: Unkonwn
  PRODUCT_NAME: BE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check server configuration
      run: |
        echo "-------------------------------CPU信息-------------------------------------------"
        echo
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo "CPU核心及版本信息:$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c)"
        echo
        echo "-------------------------------内存信息-------------------------------------------"
        echo
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo
        echo "-------------------------------硬盘信息--------------------------------------------"
        echo
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)"
        echo "硬盘详情："
        df -Th
      
    - name: Initialization environment
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo apt -y autoremove --purge
        sudo apt clean && sudo apt autoclean
        sudo systemctl daemon-reload
        echo "DATE=$(date "+%Y%m%d_%H%M%S")" >> $GITHUB_ENV
        df -Th
  
    - name: Clone source code
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        path: openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a
      
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Add Argon Theme
      run: |
        cd openwrt/package
        git clone https://github.com/jerrykuku/luci-theme-argon.git
    
    - name: Load custom configuration
      run: mv config/${{ env.PRODUCT_NAME }}.config openwrt/.config

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        make -j$(nproc) || make -j1 || make -j1 V=s
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*CONFIG_TARGET_(.*)_DEVICE.*/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
    
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.PRODUCT_NAME }}_bin_${{ env.DEVICE_NAME }}_${{ env.DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      run: |
        cd $GITHUB_WORKSPACE/openwrt/bin/packages
        tar -zcvf Packages.tar.gz ./*
        cp Packages.tar.gz $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt-${{ env.PRODUCT_NAME }}_firmware_${{ env.DEVICE_NAME }}_${{ env.DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Create release
      id: release
      uses: ncipollo/release-action@main
      with:
        tag: OpenWrt-${{ env.PRODUCT_NAME }}_${{ env.DEVICE_NAME }}_${{ env.DATE }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
